# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Fri Sep 26 15:20:52 IST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design multiplier

create_clock -name "clk" -period 5.0 -waveform {0.0 2.5} [get_ports clk]
set_load -pin_load 0.01 [get_ports valid_out]
set_load -pin_load 0.01 [get_ports {y[31]}]
set_load -pin_load 0.01 [get_ports {y[30]}]
set_load -pin_load 0.01 [get_ports {y[29]}]
set_load -pin_load 0.01 [get_ports {y[28]}]
set_load -pin_load 0.01 [get_ports {y[27]}]
set_load -pin_load 0.01 [get_ports {y[26]}]
set_load -pin_load 0.01 [get_ports {y[25]}]
set_load -pin_load 0.01 [get_ports {y[24]}]
set_load -pin_load 0.01 [get_ports {y[23]}]
set_load -pin_load 0.01 [get_ports {y[22]}]
set_load -pin_load 0.01 [get_ports {y[21]}]
set_load -pin_load 0.01 [get_ports {y[20]}]
set_load -pin_load 0.01 [get_ports {y[19]}]
set_load -pin_load 0.01 [get_ports {y[18]}]
set_load -pin_load 0.01 [get_ports {y[17]}]
set_load -pin_load 0.01 [get_ports {y[16]}]
set_load -pin_load 0.01 [get_ports {y[15]}]
set_load -pin_load 0.01 [get_ports {y[14]}]
set_load -pin_load 0.01 [get_ports {y[13]}]
set_load -pin_load 0.01 [get_ports {y[12]}]
set_load -pin_load 0.01 [get_ports {y[11]}]
set_load -pin_load 0.01 [get_ports {y[10]}]
set_load -pin_load 0.01 [get_ports {y[9]}]
set_load -pin_load 0.01 [get_ports {y[8]}]
set_load -pin_load 0.01 [get_ports {y[7]}]
set_load -pin_load 0.01 [get_ports {y[6]}]
set_load -pin_load 0.01 [get_ports {y[5]}]
set_load -pin_load 0.01 [get_ports {y[4]}]
set_load -pin_load 0.01 [get_ports {y[3]}]
set_load -pin_load 0.01 [get_ports {y[2]}]
set_load -pin_load 0.01 [get_ports {y[1]}]
set_load -pin_load 0.01 [get_ports {y[0]}]
set_false_path -from [get_ports rst_n]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports valid_in]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {a[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {b[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports valid_out]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {y[0]}]
set_input_transition 0.1 [get_ports valid_in]
set_input_transition 0.1 [get_ports {a[15]}]
set_input_transition 0.1 [get_ports {a[14]}]
set_input_transition 0.1 [get_ports {a[13]}]
set_input_transition 0.1 [get_ports {a[12]}]
set_input_transition 0.1 [get_ports {a[11]}]
set_input_transition 0.1 [get_ports {a[10]}]
set_input_transition 0.1 [get_ports {a[9]}]
set_input_transition 0.1 [get_ports {a[8]}]
set_input_transition 0.1 [get_ports {a[7]}]
set_input_transition 0.1 [get_ports {a[6]}]
set_input_transition 0.1 [get_ports {a[5]}]
set_input_transition 0.1 [get_ports {a[4]}]
set_input_transition 0.1 [get_ports {a[3]}]
set_input_transition 0.1 [get_ports {a[2]}]
set_input_transition 0.1 [get_ports {a[1]}]
set_input_transition 0.1 [get_ports {a[0]}]
set_input_transition 0.1 [get_ports {b[15]}]
set_input_transition 0.1 [get_ports {b[14]}]
set_input_transition 0.1 [get_ports {b[13]}]
set_input_transition 0.1 [get_ports {b[12]}]
set_input_transition 0.1 [get_ports {b[11]}]
set_input_transition 0.1 [get_ports {b[10]}]
set_input_transition 0.1 [get_ports {b[9]}]
set_input_transition 0.1 [get_ports {b[8]}]
set_input_transition 0.1 [get_ports {b[7]}]
set_input_transition 0.1 [get_ports {b[6]}]
set_input_transition 0.1 [get_ports {b[5]}]
set_input_transition 0.1 [get_ports {b[4]}]
set_input_transition 0.1 [get_ports {b[3]}]
set_input_transition 0.1 [get_ports {b[2]}]
set_input_transition 0.1 [get_ports {b[1]}]
set_input_transition 0.1 [get_ports {b[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.05 [get_clocks clk]
set_clock_uncertainty -hold 0.02 [get_clocks clk]
